-- CreateEnum
CREATE TYPE "AchievementType" AS ENUM ('SELF_CLAIMED', 'SELF_WITHDRAWN', 'BECAME_TIPPER', 'LINKED_EMAIL', 'LINKED_WALLET', 'SET_NAME', 'SET_AVATAR_URL', 'SET_LIGHTNING_ADDRESS', 'CREATED_TIP', 'FUNDED_TIP', 'TIP_CLAIMED', 'TIP_WITHDRAWN', 'WEBLN_FUNDED', 'WEBLN_WITHDRAWN', 'MANUAL_WITHDRAWN', 'LNURL_WITHDRAWN');

-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'ACHIEVEMENT_UNLOCKED';

-- AlterTable
ALTER TABLE "Notification" ADD COLUMN     "achievementId" TEXT;

-- CreateTable
CREATE TABLE "Achievement" (
    "type" "AchievementType" NOT NULL,
    "userId" TEXT NOT NULL,
    "created" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Achievement_pkey" PRIMARY KEY ("userId","type")
);

-- AddForeignKey
ALTER TABLE "Achievement" ADD CONSTRAINT "Achievement_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
