name: Fly Deploy (staging)
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app (staging)
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd app && flyctl deploy --depot=false -c fly-staging.toml --remote-only --build-secret DATABASE_URL="${{ secrets.DATABASE_URL_STAGING }}" --build-secret SENTRY_AUTH_TOKEN="${{ secrets.SENTRY_AUTH_TOKEN }}" --build-secret SENTRY_DSN="${{ secrets.SENTRY_DSN }}"
